apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qp-deployment
  namespace: qp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qp
  template:
    metadata:
      labels:
        app: qp
    spec:
      containers:
      - image: spbdocker03:5000/qp:||version||
        name: qp
        env:
        - name: Properties__QpConfigUrl
          value: http://mscdev02:54321
        - name: Properties__QpConfigToken
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJRUC5Db25maWd1cmF0aW9uU2VydmljZS5Jc3N1ZXIiLCJleHAiOjE1Nzg1ODM4NjIsImF1ZCI6IlFQLkNvbmZpZ3VyYXRpb25TZXJ2aWNlLkF1ZGllbmNlIn0.wN-we_Wezxtv3rtLn3mEQ9tZngPwfgn45Ta7kLfKO-Q
        ports:
        - containerPort: 80
        resources: 
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qp-service
  namespace: qp-ns
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: qp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qp-ingress
  namespace: qp-ns
spec:
  rules:
  - host: qp.dev.qsupport.ru
    http:
      paths:
      - backend:
          serviceName: qp-service
          servicePort: 80
