//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class ContextMenuItemDAL
    {
        public int ContextMenuId { get; set; }
        public int ActionId { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }
        public string Icon { get; set; }
        public string IconDisabled { get; set; }
        public bool HasBottomSeparator { get; set; }
    
        public virtual ContextMenuDAL ContextMenu { get; set; }
        public virtual BackendActionDAL Action { get; set; }
    }
}
