//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class ContentFolderDAL :  IQpEntityObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentFolderDAL()
        {
            this.ContentFolderAccess = new HashSet<ContentFolderAccessDAL>();
            this.ContentFolder1 = new HashSet<ContentFolderDAL>();
        }
    
        public decimal ContentId { get; set; }
        public decimal Id { get; set; }
        public Nullable<decimal> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Filter { get; set; }
        public string Path { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
    
        public virtual ContentDAL Content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentFolderAccessDAL> ContentFolderAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentFolderDAL> ContentFolder1 { get; set; }
        public virtual ContentFolderDAL ContentFolder2 { get; set; }
        public virtual UserDAL LastModifiedByUser { get; set; }
    }
}
