//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class ContainerDAL
    {
        public decimal ObjectId { get; set; }
        public decimal ContentId { get; set; }
        public Nullable<decimal> AllowOrderDynamic { get; private set; }
        public string OrderStatic { get; set; }
        public string OrderDynamic { get; set; }
        public string FilterValue { get; set; }
        public string SelectStart { get; set; }
        public string SelectTotal { get; set; }
        public decimal ScheduleDependence { get; set; }
        public decimal RotateContent { get; set; }
        public decimal ApplySecurity { get; set; }
        public decimal ShowArchived { get; set; }
        public string CursorType { get; set; }
        public string CursorLocation { get; set; }
        public string LockType { get; set; }
        public Nullable<System.DateTime> Locked { get; set; }
        public Nullable<decimal> LockedBy { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public bool EnableCacheInvalidation { get; set; }
        public string DynamicContentVariable { get; set; }
        public Nullable<decimal> StartLevel { get; set; }
        public Nullable<decimal> EndLevel { get; set; }
        public Nullable<bool> UseLevelFiltration { get; set; }
        public bool ReturnLastModified { get; set; }
    
        public virtual ContentDAL Content { get; set; }
        public virtual UserDAL Users { get; set; }
        public virtual ObjectDAL Object { get; set; }
        public virtual PermissionLevelDAL EndPermissionLevel { get; set; }
        public virtual PermissionLevelDAL StartPermissionLevel { get; set; }
    }
}
