//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class ExternalNotificationDAL
    {
        public decimal Id { get; set; }
        public string EventName { get; set; }
        public decimal ArticleId { get; set; }
        public System.DateTime Created { get; set; }
        public string Url { get; set; }
        public decimal Tries { get; set; }
        public string NewXml { get; set; }
        public string OldXml { get; set; }
        public bool Sent { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<decimal> ContentId { get; set; }
        public Nullable<decimal> SiteId { get; set; }
    }
}
