//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Quantumart.QP8.DAL
{
    
    // ReSharper disable CollectionNeverUpdated.Global
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    // ReSharper disable UnusedAutoPropertyAccessor.Global
    public partial class FieldTypeDAL
    {
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string DatabaseType { get; set; }
        public string InputType { get; set; }
        public string CheckFunction { get; set; }
        public string Icon { get; set; }
    
        public ICollection<FieldDAL> Field { get; set; }
    }
        public class FieldTypeDALConfiguration : IEntityTypeConfiguration<FieldTypeDAL>
        {
            public void Configure(EntityTypeBuilder<FieldTypeDAL> builder)
            {
                builder.ToTable("ATTRIBUTE_TYPE");
    
                builder.Property(x => x.Id).HasColumnName("ATTRIBUTE_TYPE_ID");
				builder.Property(x => x.Name).HasColumnName("TYPE_NAME");
				builder.Property(x => x.Description).HasColumnName("DESCRIPTION");
				builder.Property(x => x.Image).HasColumnName("TYPE_IMAGE");
				builder.Property(x => x.DatabaseType).HasColumnName("DATABASE_TYPE");
				builder.Property(x => x.InputType).HasColumnName("INPUT_TYPE");
				builder.Property(x => x.CheckFunction).HasColumnName("CHECK_FUNCTION");
				builder.Property(x => x.Icon).HasColumnName("ICON");
				
    
                builder.HasKey(x => x.Id);
    
                builder.HasMany(x => x.Field).WithOne(y => y.Type).HasForeignKey(y => y.TypeId);
    			
            }
        }
}
