//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class LanguagesDAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LanguagesDAL()
        {
            this.Translations = new HashSet<TranslationsDAL>();
            this.Users = new HashSet<UserDAL>();
        }
    
        public decimal LanguageId { get; set; }
        public string LanguageName { get; set; }
        public decimal LanguagePt { get; set; }
        public decimal Locale { get; set; }
        public decimal Codepage { get; set; }
        public string Charset { get; set; }
        public string GeneralDateFormat { get; set; }
        public string LongDateFormat { get; set; }
        public string ShortDateFormat { get; set; }
        public string LongTimeFormat { get; set; }
        public string ShortTimeFormat { get; set; }
        public bool Direction { get; set; }
        public string IsoCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranslationsDAL> Translations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDAL> Users { get; set; }
    }
}
