//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Quantumart.QP8.DAL
{
    
    // ReSharper disable CollectionNeverUpdated.Global
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    // ReSharper disable UnusedAutoPropertyAccessor.Global
    public partial class NotificationsSentDAL
    {
    
        public decimal UserId { get; set; }
        public decimal NotificationId { get; set; }
        public decimal ArticleId { get; set; }
        public System.DateTime Sent { get; set; }
        public string EventTxt { get; set; }
    }
        public class NotificationsSentDALConfiguration : IEntityTypeConfiguration<NotificationsSentDAL>
        {
            public void Configure(EntityTypeBuilder<NotificationsSentDAL> builder)
            {
                builder.ToTable("notifications_sent");
    
                builder.Property(x => x.UserId).HasColumnName("user_id");
				builder.Property(x => x.NotificationId).HasColumnName("notification_id");
				builder.Property(x => x.ArticleId).HasColumnName("content_item_id");
				builder.Property(x => x.Sent).HasColumnName("sent");
				builder.Property(x => x.EventTxt).HasColumnName("event_txt");
				
    
                builder.HasKey(x => new { x.UserId, x.Sent });

    
                
            }
        }
}
