//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class NotificationsDAL :  IQpEntityObject
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public decimal ContentId { get; set; }
        public Nullable<decimal> FormatId { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<decimal> GroupId { get; set; }
        public bool ForCreate { get; set; }
        public bool ForModify { get; set; }
        public bool ForRemove { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
        public Nullable<bool> ForStatusChanged { get; set; }
        public Nullable<bool> ForFrontend { get; set; }
        public Nullable<decimal> NotifyOnStatusTypeId { get; set; }
        public Nullable<decimal> EmailFieldId { get; set; }
        public decimal NoEmail { get; set; }
        public bool SendFiles { get; set; }
        public Nullable<decimal> WorkflowId { get; set; }
        public decimal FromBackenduserId { get; set; }
        public bool FromBackenduser { get; set; }
        public bool FromDefaultName { get; set; }
        public string FromUserEmail { get; set; }
        public string FromUserName { get; set; }
        public bool ForStatusPartiallyChanged { get; set; }
        public bool UseQaMail { get; set; }
        public bool IsExternal { get; set; }
        public string ExternalUrl { get; set; }
        public bool ForDelayedPublication { get; set; }
        public bool UseService { get; set; }
    
        public virtual ContentDAL Content { get; set; }
        public virtual FieldDAL EmailField { get; set; }
        public virtual UserDAL FromUser { get; set; }
        public virtual StatusTypeDAL OnStatusType { get; set; }
        public virtual ObjectFormatDAL Format { get; set; }
        public virtual UserGroupDAL ToUserGroup { get; set; }
        public virtual UserDAL ToUser { get; set; }
        public virtual WorkflowDAL Workflow { get; set; }
        public virtual UserDAL LastModifiedByUser { get; set; }
    }
}
