//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class NotificationsSentDAL
    {
        public decimal UserId { get; set; }
        public decimal NotificationId { get; set; }
        public decimal ArticleId { get; set; }
        public System.DateTime Sent { get; set; }
        public string EventTxt { get; set; }
    }
}
