//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class ObjectFormatDAL :  IQpEntityObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectFormatDAL()
        {
            this.Notifications = new HashSet<NotificationsDAL>();
            this.Object1 = new HashSet<ObjectDAL>();
            this.ObjectFormatVersion = new HashSet<ObjectFormatVersionDAL>();
            this.PageTraceFormat = new HashSet<PageTraceFormatDAL>();
        }
    
        public decimal Id { get; set; }
        public decimal ObjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
        public string FormatBody { get; set; }
        public Nullable<decimal> NetLanguageId { get; set; }
        public string NetFormatName { get; set; }
        public string CodeBehind { get; set; }
        public Nullable<System.DateTime> Locked { get; set; }
        public Nullable<decimal> LockedBy { get; set; }
        public System.DateTime Assembled { get; set; }
        public bool AssembleInLive { get; set; }
        public bool AssembleInStage { get; set; }
        public bool AssembleNotificationInLive { get; set; }
        public bool AssembleNotificationInStage { get; set; }
        public bool AssemblePreviewInLive { get; set; }
        public bool AssemblePreviewInStage { get; set; }
        public string TagName { get; set; }
        public bool PermanentLock { get; set; }
    
        public virtual NetLanguagesDAL NetLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationsDAL> Notifications { get; set; }
        public virtual ObjectDAL Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectDAL> Object1 { get; set; }
        public virtual UserDAL LockedByUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectFormatVersionDAL> ObjectFormatVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageTraceFormatDAL> PageTraceFormat { get; set; }
        public virtual UserDAL LastModifiedByUser { get; set; }
    }
}
