//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class ObjectDAL :  IQpEntityObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectDAL()
        {
            this.ChildObjectFormats = new HashSet<ObjectFormatDAL>();
            this.InheritedObjects = new HashSet<ObjectDAL>();
            this.ObjectValues = new HashSet<ObjectValuesDAL>();
            this.StatusType = new HashSet<StatusTypeDAL>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> ParentObjectId { get; set; }
        public Nullable<decimal> PageTemplateId { get; set; }
        public Nullable<decimal> PageId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> DefaultFormatId { get; set; }
        public string Description { get; set; }
        public decimal TypeId { get; set; }
        public decimal UseDefaultValues { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
        public decimal AllowStageEdit { get; set; }
        public bool Global { get; set; }
        public string NetName { get; set; }
        public Nullable<System.DateTime> Locked { get; set; }
        public Nullable<decimal> LockedBy { get; set; }
        public bool EnableViewstate { get; set; }
        public string ControlCustomClass { get; set; }
        public bool DisableDatabind { get; set; }
        public bool PermanentLock { get; set; }
    
        public virtual ContainerDAL Container { get; set; }
        public virtual ContentFormDAL ContentForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectFormatDAL> ChildObjectFormats { get; set; }
        public virtual UserDAL LockedByUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectDAL> InheritedObjects { get; set; }
        public virtual ObjectDAL ObjectInheritedFrom { get; set; }
        public virtual ObjectTypeDAL ObjectType { get; set; }
        public virtual PageDAL Page { get; set; }
        public virtual PageTemplateDAL PageTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectValuesDAL> ObjectValues { get; set; }
        public virtual ObjectFormatDAL DefaultFormat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusTypeDAL> StatusType { get; set; }
        public virtual UserDAL LastModifiedByUser { get; set; }
    }
}
