//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class PageTraceFormatDAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageTraceFormatDAL()
        {
            this.PageTraceFormat1 = new HashSet<PageTraceFormatDAL>();
            this.PageTraceFormatValues = new HashSet<PageTraceFormatValuesDAL>();
        }
    
        public decimal TraceFormatId { get; set; }
        public decimal FormatId { get; set; }
        public Nullable<decimal> ParentTraceFormatId { get; set; }
        public decimal TraceId { get; set; }
        public decimal Number { get; set; }
        public decimal Duration { get; set; }
    
        public virtual ObjectFormatDAL ObjectFormat { get; set; }
        public virtual PageTraceDAL PageTrace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageTraceFormatDAL> PageTraceFormat1 { get; set; }
        public virtual PageTraceFormatDAL PageTraceFormat2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageTraceFormatValuesDAL> PageTraceFormatValues { get; set; }
    }
}
