//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class StyleDAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StyleDAL()
        {
            this.StyleAttribute = new HashSet<StyleAttributeDAL>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> TagId { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
        public Nullable<decimal> SiteId { get; set; }
        public bool Direct { get; set; }
    
        public virtual SiteDAL Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StyleAttributeDAL> StyleAttribute { get; set; }
    }
}
