//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class UserQueryContentsDAL
    {
        public decimal VirtualContentId { get; set; }
        public decimal RealContentId { get; set; }
        public Nullable<bool> IsIdSource { get; set; }
    
        public virtual ContentDAL Content { get; set; }
        public virtual ContentDAL Content1 { get; set; }
    }
}
