//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class VeCommandDAL :  IQpEntityObject
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public int RowOrder { get; set; }
        public int ToolbarInRowOrder { get; set; }
        public int GroupInToolbarOrder { get; set; }
        public int CommandInGroupOrder { get; set; }
        public bool On { get; set; }
        public Nullable<decimal> PluginId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
    
        public virtual VePluginDAL VePlugin { get; set; }
        public virtual UserDAL LastModifiedByUser { get; set; }
    }
}
