//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class VeStyleDAL :  IQpEntityObject
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Tag { get; set; }
        public int Order { get; set; }
        public string OverridesTag { get; set; }
        public bool IsFormat { get; set; }
        public bool IsSystem { get; set; }
        public string Attributes { get; set; }
        public string Styles { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
    
        public virtual UserDAL LastModifiedByUser { get; set; }
    }
}
