//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Quantumart.QP8.DAL
{
    
    public partial class XmlDbUpdateLogEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XmlDbUpdateLogEntity()
        {
            this.XML_DB_UPDATE_ACTIONS = new HashSet<XmlDbUpdateActionsLogEntity>();
        }
    
        public int Id { get; set; }
        public System.DateTime Applied { get; set; }
        public string Hash { get; set; }
        public string FileName { get; set; }
        public int UserId { get; set; }
        public string Body { get; set; }
        public string Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XmlDbUpdateActionsLogEntity> XML_DB_UPDATE_ACTIONS { get; set; }
    }
}
