DO $$ BEGIN

create view content_attribute_type(database_type, input_type, icon, type_name, attribute_id, content_id, attribute_name,
                                   format_mask, input_mask, attribute_size, default_value, attribute_type_id,
                                   related_attribute_id, index_flag, description, modified, created, last_modified_by,
                                   attribute_order, required, permanent_flag, primary_flag, relation_condition,
                                   display_as_radio_button, view_in_list, readonly_flag, allow_stage_edit,
                                   attribute_configuration, related_image_attribute_id, persistent_attr_id,
                                   join_attr_id, link_id, default_blob_value, auto_load, friendly_name,
                                   use_site_library, use_archive_articles, auto_expand, relation_page_size, doctype,
                                   full_page, rename_matched, subfolder, disable_version_control, map_as_property,
                                   net_attribute_name, net_back_attribute_name, p_enter_mode, use_english_quotes,
                                   back_related_attribute_id, is_long, external_css, root_element_class, use_for_tree,
                                   auto_check_children, aggregated, classifier_attribute_id, is_classifier, changeable,
                                   use_relation_security, copy_permissions_to_children, enum_values,
                                   show_as_radio_button, use_for_default_filtration, tree_order_field,
                                   parent_attribute_id, hide, override, use_for_context, use_for_variations,
                                   order_by_title, field_title_count, include_relations_in_title,
                                   use_in_child_content_filter, optimize_for_hierarchy, is_localization,
                                   use_separate_reverse_views, disable_list_auto_wrap, ta_highlight_type,
                                   max_data_list_item_count) as
SELECT at.database_type,
       at.input_type,
       at.icon,
       at.type_name,
       ca.attribute_id,
       ca.content_id,
       ca.attribute_name,
       ca.format_mask,
       ca.input_mask,
       ca.attribute_size,
       ca.default_value,
       ca.attribute_type_id,
       ca.related_attribute_id,
       ca.index_flag,
       ca.description,
       ca.modified,
       ca.created,
       ca.last_modified_by,
       ca.attribute_order,
       ca.required,
       ca.permanent_flag,
       ca.primary_flag,
       ca.relation_condition,
       ca.display_as_radio_button,
       ca.view_in_list,
       ca.readonly_flag,
       ca.allow_stage_edit,
       ca.attribute_configuration,
       ca.related_image_attribute_id,
       ca.persistent_attr_id,
       ca.join_attr_id,
       ca.link_id,
       ca.default_blob_value,
       ca.auto_load,
       ca.friendly_name,
       ca.use_site_library,
       ca.use_archive_articles,
       ca.auto_expand,
       ca.relation_page_size,
       ca.doctype,
       ca.full_page,
       ca.rename_matched,
       ca.subfolder,
       ca.disable_version_control,
       ca.map_as_property,
       ca.net_attribute_name,
       ca.net_back_attribute_name,
       ca.p_enter_mode,
       ca.use_english_quotes,
       ca.back_related_attribute_id,
       ca.is_long,
       ca.external_css,
       ca.root_element_class,
       ca.use_for_tree,
       ca.auto_check_children,
       ca.aggregated,
       ca.classifier_attribute_id,
       ca.is_classifier,
       ca.changeable,
       ca.use_relation_security,
       ca.copy_permissions_to_children,
       ca.enum_values,
       ca.show_as_radio_button,
       ca.use_for_default_filtration,
       ca.tree_order_field,
       ca.parent_attribute_id,
       ca.hide,
       ca.override,
       ca.use_for_context,
       ca.use_for_variations,
       ca.order_by_title,
       ca.field_title_count,
       ca.include_relations_in_title,
       ca.use_in_child_content_filter,
       ca.optimize_for_hierarchy,
       ca.is_localization,
       ca.use_separate_reverse_views,
       ca.disable_list_auto_wrap,
       ca.ta_highlight_type,
       ca.max_data_list_item_count
FROM (content_attribute ca
         JOIN attribute_type at ON ((ca.attribute_type_id = at.attribute_type_id)));


EXCEPTION
    WHEN duplicate_table THEN null;
END $$;


