create or replace view VIRTUAL_ATTR_BASE_ATTR_RELATION AS
	WITH V2BREL AS
		(SELECT USER_QUERY_ATTR_ID as VIRTUAL_ATTR_ID
			  ,BASE_ATTR_ID as BASE_ATTR_ID
		FROM V_USER_QUERY_ATTRS
		UNION ALL
		SELECT virtual_attr_id as VIRTUAL_ATTR_ID
			  ,union_attr_id as BASE_ATTR_ID
		FROM union_attrs
		UNION ALL
		select ATTRIBUTE_ID as VIRTUAL_ATTR_ID,
		persistent_attr_id as BASE_ATTR_ID
		from CONTENT_ATTRIBUTE
		where persistent_attr_id is not null)
	select AR.BASE_ATTR_ID, BC.CONTENT_ID BASE_CNT_ID, BC.VIRTUAL_TYPE BASE_CNT_VTYPE,
	AR.VIRTUAL_ATTR_ID, VC.CONTENT_ID VIRTUAL_CNT_ID, VC.VIRTUAL_TYPE VIRTUAL_CNT_VTYPE
	from V2BREL AR
	JOIN CONTENT_ATTRIBUTE BA ON BA.ATTRIBUTE_ID = AR.BASE_ATTR_ID
	JOIN CONTENT_ATTRIBUTE VA ON VA.ATTRIBUTE_ID = AR.VIRTUAL_ATTR_ID
	JOIN CONTENT BC ON BA.CONTENT_ID = BC.CONTENT_ID
	JOIN CONTENT VC ON VA.CONTENT_ID = VC.CONTENT_ID;

alter table v_user_query_attrs
    owner to postgres;
