IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SITE' AND COLUMN_NAME = 'EXTERNAL_DEVELOPMENT') 
BEGIN
    ALTER TABLE SITE ADD EXTERNAL_DEVELOPMENT BIT NOT NULL CONSTRAINT DF_SITE_EXTERNAL_DEVELOPMENT DEFAULT 1  
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SITE' AND COLUMN_NAME = 'DOWNLOAD_EF_SOURCE') 
BEGIN
    ALTER TABLE SITE ADD DOWNLOAD_EF_SOURCE BIT NOT NULL CONSTRAINT DF_SITE_DOWNLOAD_EF_SOURCE DEFAULT 0  
END