//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantumart.QP8.WebMvc.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogOnStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogOnStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quantumart.QP8.WebMvc.Resources.Controllers.LogOnStrings", typeof(LogOnStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is blocked!.
        /// </summary>
        internal static string ErrorMessage_AccountBlocked {
            get {
                return ResourceManager.GetString("ErrorMessage_AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not exist!.
        /// </summary>
        internal static string ErrorMessage_AccountNotExist {
            get {
                return ResourceManager.GetString("ErrorMessage_AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code does not exist!.
        /// </summary>
        internal static string ErrorMessage_CustomerCodeNotExist {
            get {
                return ResourceManager.GetString("ErrorMessage_CustomerCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You not entered customer code!.
        /// </summary>
        internal static string ErrorMessage_NotEnteredCustomerCode {
            get {
                return ResourceManager.GetString("ErrorMessage_NotEnteredCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You not entered login!.
        /// </summary>
        internal static string ErrorMessage_NotEnteredLogin {
            get {
                return ResourceManager.GetString("ErrorMessage_NotEnteredLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You not entered password!.
        /// </summary>
        internal static string ErrorMessage_NotEnteredPassword {
            get {
                return ResourceManager.GetString("ErrorMessage_NotEnteredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been expired. Please log out..
        /// </summary>
        internal static string ErrorMessage_SessionExpired {
            get {
                return ResourceManager.GetString("ErrorMessage_SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During authentication, an unknown error occurred!.
        /// </summary>
        internal static string ErrorMessage_UnknownAuthenticationError {
            get {
                return ResourceManager.GetString("ErrorMessage_UnknownAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered wrong password!.
        /// </summary>
        internal static string ErrorMessage_WrongPassword {
            get {
                return ResourceManager.GetString("ErrorMessage_WrongPassword", resourceCulture);
            }
        }
    }
}
