//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantumart.QP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quantumart.QP8.Resources.ContentStrings", typeof(ContentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid additional context class name.
        /// </summary>
        public static string AddContextClassNameInvalidFormat {
            get {
                return ResourceManager.GetString("AddContextClassNameInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of additional context class name should not exceed {5} characters.
        /// </summary>
        public static string AddContextClassNameLengthExceeded {
            get {
                return ResourceManager.GetString("AddContextClassNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional context class name is already in using in the site.
        /// </summary>
        public static string AddContextClassNameNonUnique {
            get {
                return ResourceManager.GetString("AddContextClassNameNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional context class name is already in using in the database.
        /// </summary>
        public static string AddContextClassNameNonUniqueDB {
            get {
                return ResourceManager.GetString("AddContextClassNameNonUniqueDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional context class name.
        /// </summary>
        public static string AdditionalContextClassName {
            get {
                return ResourceManager.GetString("AdditionalContextClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Groups.
        /// </summary>
        public static string AllContentGroups {
            get {
                return ResourceManager.GetString("AllContentGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sites.
        /// </summary>
        public static string AllSites {
            get {
                return ResourceManager.GetString("AllSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive on Removal.
        /// </summary>
        public static string ArchiveOnRemoval {
            get {
                return ResourceManager.GetString("ArchiveOnRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing\Creation actions of this content arcticles is prohibited..
        /// </summary>
        public static string ArticleChangingIsProhibited {
            get {
                return ResourceManager.GetString("ArticleChangingIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Article Permissions has been enabled..
        /// </summary>
        public static string ArticlePermissionsComplete {
            get {
                return ResourceManager.GetString("ArticlePermissionsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Articles Per Page.
        /// </summary>
        public static string ArticlesNumberPerPage {
            get {
                return ResourceManager.GetString("ArticlesNumberPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Articles Per Page is not in acceptable range: from {0} to {1}.
        /// </summary>
        public static string ArticlesNumberPerPageNotInRange {
            get {
                return ResourceManager.GetString("ArticlesNumberPerPageNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add content into the site because you have no enough permissions.
        /// </summary>
        public static string CannotAddBecauseOfSecurity {
            get {
                return ResourceManager.GetString("CannotAddBecauseOfSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add content group into the site because you have no enough permissions.
        /// </summary>
        public static string CannotAddGroupBecauseOfSecurity {
            get {
                return ResourceManager.GetString("CannotAddGroupBecauseOfSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Auto Archive&quot; could not be changed because there are aggregated fields in the current content.
        /// </summary>
        public static string CannotChangeAutoArchive {
            get {
                return ResourceManager.GetString("CannotChangeAutoArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Is Async&quot; could not be changed because there are aggregated fields in the current content.
        /// </summary>
        public static string CannotChangeIsAsync {
            get {
                return ResourceManager.GetString("CannotChangeIsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow could not be changed because there are aggregated fields in the current content.
        /// </summary>
        public static string CannotChangeWorkflow {
            get {
                return ResourceManager.GetString("CannotChangeWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy content because you have no enough permissions.
        /// </summary>
        public static string CannotCopyBecauseOfSecurity {
            get {
                return ResourceManager.GetString("CannotCopyBecauseOfSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove content because you have no enough permissions.
        /// </summary>
        public static string CannotRemoveBecauseOfSecurity {
            get {
                return ResourceManager.GetString("CannotRemoveBecauseOfSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update content because you have no enough permissions.
        /// </summary>
        public static string CannotUpdateBecauseOfSecurity {
            get {
                return ResourceManager.GetString("CannotUpdateBecauseOfSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update default group.
        /// </summary>
        public static string CannotUpdateDefaultGroup {
            get {
                return ResourceManager.GetString("CannotUpdateDefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update content group because you have no enough permissions.
        /// </summary>
        public static string CannotUpdateGroupBecauseOfSecurity {
            get {
                return ResourceManager.GetString("CannotUpdateGroupBecauseOfSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear content &quot;{0}&quot;.
        /// </summary>
        public static string ClearContentStageName {
            get {
                return ResourceManager.GetString("ClearContentStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content changing actions are disabled.
        /// </summary>
        public static string ContentChangingIsProhibited {
            get {
                return ResourceManager.GetString("ContentChangingIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content could not be removed because content contains articles and the following aggregated fields: {0}.
        /// </summary>
        public static string ContentIsAggregated {
            get {
                return ResourceManager.GetString("ContentIsAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content not found (Id = {0}).
        /// </summary>
        public static string ContentNotFound {
            get {
                return ResourceManager.GetString("ContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following contents could not be removed because there are related contents in other sites: {0}.
        /// </summary>
        public static string ContentsAreSharedRelated {
            get {
                return ResourceManager.GetString("ContentsAreSharedRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following contents could not be removed because there are inherited virtual contents in other sites: {0}.
        /// </summary>
        public static string ContentsAreSharedUnionBase {
            get {
                return ResourceManager.GetString("ContentsAreSharedUnionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Default XAML Validation.
        /// </summary>
        public static string CreateDefaultXAMLValidation {
            get {
                return ResourceManager.GetString("CreateDefaultXAMLValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Versions.
        /// </summary>
        public static string CreateVersions {
            get {
                return ResourceManager.GetString("CreateVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Content.
        /// </summary>
        public static string CurrentContent {
            get {
                return ResourceManager.GetString("CurrentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle in the content graph has been found.
        /// </summary>
        public static string CyclesInContentTree {
            get {
                return ResourceManager.GetString("CyclesInContentTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Group.
        /// </summary>
        public static string DefaultContentGroup {
            get {
                return ResourceManager.GetString("DefaultContentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of description should not exceed {5} characters.
        /// </summary>
        public static string DescriptionMaxLengthExceeded {
            get {
                return ResourceManager.GetString("DescriptionMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Changing Actions.
        /// </summary>
        public static string DisableChangingActions {
            get {
                return ResourceManager.GetString("DisableChangingActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable XAML Validation.
        /// </summary>
        public static string DisableXamlValidation {
            get {
                return ResourceManager.GetString("DisableXamlValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable articles permissions.
        /// </summary>
        public static string EnableArticlesPermissions {
            get {
                return ResourceManager.GetString("EnableArticlesPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Site Sharing.
        /// </summary>
        public static string EnableSiteSharing {
            get {
                return ResourceManager.GetString("EnableSiteSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the following inherited virtual contents: {0}. Error: {1}.
        /// </summary>
        public static string ErrorInSubContent {
            get {
                return ResourceManager.GetString("ErrorInSubContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors on copying next virtual contents:.
        /// </summary>
        public static string ErrorsOnCopyingVirtualContents {
            get {
                return ResourceManager.GetString("ErrorsOnCopyingVirtualContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Articles.
        /// </summary>
        public static string ExportArticles {
            get {
                return ResourceManager.GetString("ExportArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script for form.
        /// </summary>
        public static string FormScript {
            get {
                return ResourceManager.GetString("FormScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For replication.
        /// </summary>
        public static string ForReplication {
            get {
                return ResourceManager.GetString("ForReplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of plural friendly name should not exceed {5} characters.
        /// </summary>
        public static string FriendlyPluralMaxLengthExceeded {
            get {
                return ResourceManager.GetString("FriendlyPluralMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of singular friendly name should not exceed {5} characters.
        /// </summary>
        public static string FriendlySingularMaxLengthExceeded {
            get {
                return ResourceManager.GetString("FriendlySingularMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content group name.
        /// </summary>
        public static string GroupNameInvalidFormat {
            get {
                return ResourceManager.GetString("GroupNameInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of content group name should not exceed {5} characters.
        /// </summary>
        public static string GroupNameMaxLengthExceeded {
            get {
                return ResourceManager.GetString("GroupNameMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content group name is already in using on the site.
        /// </summary>
        public static string GroupNameNonUnique {
            get {
                return ResourceManager.GetString("GroupNameNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter content group name.
        /// </summary>
        public static string GroupNameNotEntered {
            get {
                return ResourceManager.GetString("GroupNameNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content group not found (Id = {0}).
        /// </summary>
        public static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        public static string Hierarchy {
            get {
                return ResourceManager.GetString("Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import articles.
        /// </summary>
        public static string ImportArticles {
            get {
                return ResourceManager.GetString("ImportArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are invalid type columns: {0}.
        /// </summary>
        public static string InvalidColumnsInUserQuery {
            get {
                return ResourceManager.GetString("InvalidColumnsInUserQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use separate query for United View.
        /// </summary>
        public static string IsAltUserQueryUsed {
            get {
                return ResourceManager.GetString("IsAltUserQueryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string JoinFields {
            get {
                return ResourceManager.GetString("JoinFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check Fields.
        /// </summary>
        public static string JoinFieldsNotEntered {
            get {
                return ResourceManager.GetString("JoinFieldsNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source content.
        /// </summary>
        public static string JoinRoot {
            get {
                return ResourceManager.GetString("JoinRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Parameters.
        /// </summary>
        public static string Legend_BasicParameters {
            get {
                return ResourceManager.GetString("Legend_BasicParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client scripts.
        /// </summary>
        public static string Legend_ClientScripts {
            get {
                return ResourceManager.GetString("Legend_ClientScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Validation.
        /// </summary>
        public static string Legend_CustomValidation {
            get {
                return ResourceManager.GetString("Legend_CustomValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        public static string Legend_FriendlyName {
            get {
                return ResourceManager.GetString("Legend_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINQ Mapping Parameters.
        /// </summary>
        public static string Legend_LinqParameters {
            get {
                return ResourceManager.GetString("Legend_LinqParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Control.
        /// </summary>
        public static string Legend_VersionControl {
            get {
                return ResourceManager.GetString("Legend_VersionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Content Parameters.
        /// </summary>
        public static string Legend_VirtualContentParameters {
            get {
                return ResourceManager.GetString("Legend_VirtualContentParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Legend_Workflow {
            get {
                return ResourceManager.GetString("Legend_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Content.
        /// </summary>
        public static string Link_AddNewContent {
            get {
                return ResourceManager.GetString("Link_AddNewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Field.
        /// </summary>
        public static string Link_AddNewField {
            get {
                return ResourceManager.GetString("Link_AddNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map as class.
        /// </summary>
        public static string MapAsClass {
            get {
                return ResourceManager.GetString("MapAsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Stored Versions.
        /// </summary>
        public static string MaximumNumberOfStoredVersions {
            get {
                return ResourceManager.GetString("MaximumNumberOfStoredVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content name.
        /// </summary>
        public static string NameInvalidFormat {
            get {
                return ResourceManager.GetString("NameInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of content name should not exceed {5} characters.
        /// </summary>
        public static string NameMaxLengthExceeded {
            get {
                return ResourceManager.GetString("NameMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content name is already in using on the site.
        /// </summary>
        public static string NameNonUnique {
            get {
                return ResourceManager.GetString("NameNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content name is already in using in the database.
        /// </summary>
        public static string NameNonUniqueDB {
            get {
                return ResourceManager.GetString("NameNonUniqueDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter content name.
        /// </summary>
        public static string NameNotEntered {
            get {
                return ResourceManager.GetString("NameNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (plural).
        /// </summary>
        public static string NamePlural {
            get {
                return ResourceManager.GetString("NamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plural LINQ name.
        /// </summary>
        public static string NamePluralInvalidFormat {
            get {
                return ResourceManager.GetString("NamePluralInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of plural LINQ name should not exceed {5} characters.
        /// </summary>
        public static string NamePluralMaxLengthExceeded {
            get {
                return ResourceManager.GetString("NamePluralMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural LINQ name is already in using on the site.
        /// </summary>
        public static string NamePluralNonUnique {
            get {
                return ResourceManager.GetString("NamePluralNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural LINQ name is already in using in the database.
        /// </summary>
        public static string NamePluralNonUniqueDB {
            get {
                return ResourceManager.GetString("NamePluralNonUniqueDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter plural LINQ name.
        /// </summary>
        public static string NamePluralNotEntered {
            get {
                return ResourceManager.GetString("NamePluralNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (singular).
        /// </summary>
        public static string NameSingular {
            get {
                return ResourceManager.GetString("NameSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid singular LINQ name.
        /// </summary>
        public static string NameSingularInvalidFormat {
            get {
                return ResourceManager.GetString("NameSingularInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of singular LINQ name should not exceed {5} characters.
        /// </summary>
        public static string NameSingularMaxLengthExceeded {
            get {
                return ResourceManager.GetString("NameSingularMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singular LINQ name name is already in using on the site.
        /// </summary>
        public static string NameSingularNonUnique {
            get {
                return ResourceManager.GetString("NameSingularNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singular LINQ name name is already in using in the database.
        /// </summary>
        public static string NameSingularNonUniqueDB {
            get {
                return ResourceManager.GetString("NameSingularNonUniqueDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter singular LINQ name.
        /// </summary>
        public static string NameSingularNotEntered {
            get {
                return ResourceManager.GetString("NameSingularNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not all mandatory columns in query. {0} are expected..
        /// </summary>
        public static string NotAllMandatoryColumnsInUserQuery {
            get {
                return ResourceManager.GetString("NotAllMandatoryColumnsInUserQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workflow.
        /// </summary>
        public static string NoWorkflow {
            get {
                return ResourceManager.GetString("NoWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not allowed for aggregated content..
        /// </summary>
        public static string OperationIsNotAllowedForAggregated {
            get {
                return ResourceManager.GetString("OperationIsNotAllowedForAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not allowed for aggregated contents &quot;{0}&quot;..
        /// </summary>
        public static string OperationIsNotAllowedForAggregateds {
            get {
                return ResourceManager.GetString("OperationIsNotAllowedForAggregateds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not allowed for root content..
        /// </summary>
        public static string OperationIsNotAllowedForRoot {
            get {
                return ResourceManager.GetString("OperationIsNotAllowedForRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Content.
        /// </summary>
        public static string ParentContent {
            get {
                return ResourceManager.GetString("ParentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string ParentSiteName {
            get {
                return ResourceManager.GetString("ParentSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural.
        /// </summary>
        public static string Plural {
            get {
                return ResourceManager.GetString("Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating USER QUERY structure.
        /// </summary>
        public static string RebuildUserQueryStageName {
            get {
                return ResourceManager.GetString("RebuildUserQueryStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing views.
        /// </summary>
        public static string RebuildVirtualContentViewsStageName {
            get {
                return ResourceManager.GetString("RebuildVirtualContentViewsStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content could not be removed because there are following related contents: {0}.
        /// </summary>
        public static string RelatedContentsExist {
            get {
                return ResourceManager.GetString("RelatedContentsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing content &quot;{0}&quot;.
        /// </summary>
        public static string RemoveContentStageName {
            get {
                return ResourceManager.GetString("RemoveContentStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select content.
        /// </summary>
        public static string SelectContent {
            get {
                return ResourceManager.GetString("SelectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Content Groups.
        /// </summary>
        public static string SelectContentGroup {
            get {
                return ResourceManager.GetString("SelectContentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        public static string SelectParentContent {
            get {
                return ResourceManager.GetString("SelectParentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Site.
        /// </summary>
        public static string SelectSite {
            get {
                return ResourceManager.GetString("SelectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singular.
        /// </summary>
        public static string Singular {
            get {
                return ResourceManager.GetString("Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Source content.
        /// </summary>
        public static string SourceContentNotEntered {
            get {
                return ResourceManager.GetString("SourceContentNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Articles.
        /// </summary>
        public static string SplitArticles {
            get {
                return ResourceManager.GetString("SplitArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild virtual content.
        /// </summary>
        public static string ToRebuild {
            get {
                return ResourceManager.GetString("ToRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Source contents.
        /// </summary>
        public static string UnionBaseContentNotEntered {
            get {
                return ResourceManager.GetString("UnionBaseContentNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source contents.
        /// </summary>
        public static string UnionSourceContents {
            get {
                return ResourceManager.GetString("UnionSourceContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default filtration.
        /// </summary>
        public static string UseDefaultFiltration {
            get {
                return ResourceManager.GetString("UseDefaultFiltration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for context switching.
        /// </summary>
        public static string UseForContext {
            get {
                return ResourceManager.GetString("UseForContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string UserQuery {
            get {
                return ResourceManager.GetString("UserQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query for United View.
        /// </summary>
        public static string UserQueryAlternative {
            get {
                return ResourceManager.GetString("UserQueryAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query for United View is invalid: {0}.
        /// </summary>
        public static string UserQueryAltIsInvalid {
            get {
                return ResourceManager.GetString("UserQueryAltIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column sets and/or column types of Query and Query for United View are mismatched.
        /// </summary>
        public static string UserQueryAndAltColumnsMismatch {
            get {
                return ResourceManager.GetString("UserQueryAndAltColumnsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of column [{0}] from the table [{1}] is casted from {2} to {3}.
        /// </summary>
        public static string UserQueryColumnTypeChanged {
            get {
                return ResourceManager.GetString("UserQueryColumnTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is invalid: {0}.
        /// </summary>
        public static string UserQueryIsInvalid {
            get {
                return ResourceManager.GetString("UserQueryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Query.
        /// </summary>
        public static string UserQueryNotEntered {
            get {
                return ResourceManager.GetString("UserQueryNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The types of column [{0}] in the next tables {1} are mismatched.
        /// </summary>
        public static string UserQuerySameNameColumsHaveDiffTypes {
            get {
                return ResourceManager.GetString("UserQuerySameNameColumsHaveDiffTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content could not be removed because there are following inherited virtual contents: {0}.
        /// </summary>
        public static string VirtualSubContentsExist {
            get {
                return ResourceManager.GetString("VirtualSubContentsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Type.
        /// </summary>
        public static string VirtualType {
            get {
                return ResourceManager.GetString("VirtualType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Type cannot be changed, because there are some contents which were built on the current content.
        /// </summary>
        public static string VirtualTypeCantBeChanged {
            get {
                return ResourceManager.GetString("VirtualTypeCantBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing inheritance virtual content ({0}) &quot;{1}&quot;: {2}.
        /// </summary>
        public static string VirualSubContentProcessingError {
            get {
                return ResourceManager.GetString("VirualSubContentProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Validation.
        /// </summary>
        public static string XamlValidation {
            get {
                return ResourceManager.GetString("XamlValidation", resourceCulture);
            }
        }
    }
}
