//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantumart.QP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomActionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomActionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quantumart.QP8.Resources.CustomActionStrings", typeof(CustomActionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not found (Id = {0}).
        /// </summary>
        public static string ActionNotFound {
            get {
                return ResourceManager.GetString("ActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not found (Code = {0}).
        /// </summary>
        public static string ActionNotFoundByCode {
            get {
                return ResourceManager.GetString("ActionNotFoundByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Action Type.
        /// </summary>
        public static string ActionTypeNotSelected {
            get {
                return ResourceManager.GetString("ActionTypeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Action.
        /// </summary>
        public static string AddNewCustomAction {
            get {
                return ResourceManager.GetString("AddNewCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Parameters.
        /// </summary>
        public static string BasicParametersTitle {
            get {
                return ResourceManager.GetString("BasicParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Phrase.
        /// </summary>
        public static string ConfirmPhrase {
            get {
                return ResourceManager.GetString("ConfirmPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Confirm Phrase should not exceed {5} characters!.
        /// </summary>
        public static string ConfirmPhraseLengthExceeded {
            get {
                return ResourceManager.GetString("ConfirmPhraseLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content selection mode.
        /// </summary>
        public static string ContentSelectionMode {
            get {
                return ResourceManager.GetString("ContentSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string CustomActionEntityType {
            get {
                return ResourceManager.GetString("CustomActionEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        public static string CustomActionType {
            get {
                return ResourceManager.GetString("CustomActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action type.
        /// </summary>
        public static string DefaultActionTypeOption {
            get {
                return ResourceManager.GetString("DefaultActionTypeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select entity type.
        /// </summary>
        public static string DefaultEntityTypeOption {
            get {
                return ResourceManager.GetString("DefaultEntityTypeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Entity Type.
        /// </summary>
        public static string EntityTypeNotSelected {
            get {
                return ResourceManager.GetString("EntityTypeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has pre-action.
        /// </summary>
        public static string HasPreAction {
            get {
                return ResourceManager.GetString("HasPreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has settings.
        /// </summary>
        public static string HasSettings {
            get {
                return ResourceManager.GetString("HasSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in all  contents  except selected.
        /// </summary>
        public static string HideExceptSelectedContents {
            get {
                return ResourceManager.GetString("HideExceptSelectedContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on all sites except selected.
        /// </summary>
        public static string HideExceptSelectedSites {
            get {
                return ResourceManager.GetString("HideExceptSelectedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon URL.
        /// </summary>
        public static string IconUrl {
            get {
                return ResourceManager.GetString("IconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Icon URL format.
        /// </summary>
        public static string IconUrlInvalidFormat {
            get {
                return ResourceManager.GetString("IconUrlInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Icon URL should not exceed {5} characters!.
        /// </summary>
        public static string IconUrlMaxLengthExceeded {
            get {
                return ResourceManager.GetString("IconUrlMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string IsInterface {
            get {
                return ResourceManager.GetString("IsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string IsWindow {
            get {
                return ResourceManager.GetString("IsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of Order value must be greater than zero .
        /// </summary>
        public static string OrderIsNotInRange {
            get {
                return ResourceManager.GetString("OrderIsNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of Order is not unique for the selected Entity Type. The valid value is {0} ..
        /// </summary>
        public static string OrderValueIsNotUniq {
            get {
                return ResourceManager.GetString("OrderValueIsNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected contents.
        /// </summary>
        public static string SelectedContentIDs {
            get {
                return ResourceManager.GetString("SelectedContentIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected sites.
        /// </summary>
        public static string SelectedSiteIDs {
            get {
                return ResourceManager.GetString("SelectedSiteIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in all contents except selected.
        /// </summary>
        public static string ShowExpectSelectedContents {
            get {
                return ResourceManager.GetString("ShowExpectSelectedContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on all sites except selected.
        /// </summary>
        public static string ShowExpectSelectedSites {
            get {
                return ResourceManager.GetString("ShowExpectSelectedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in context menu.
        /// </summary>
        public static string ShowInMenu {
            get {
                return ResourceManager.GetString("ShowInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on toolbar.
        /// </summary>
        public static string ShowInToolbar {
            get {
                return ResourceManager.GetString("ShowInToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site selection mode.
        /// </summary>
        public static string SiteSelectionMode {
            get {
                return ResourceManager.GetString("SiteSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some entities have not been processed because of insufficient permissions. IDs: {0}.
        /// </summary>
        public static string SomeEntitiesNotAccessable {
            get {
                return ResourceManager.GetString("SomeEntitiesNotAccessable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Context Menu for Entity Type &apos;{0}&apos;.
        /// </summary>
        public static string ThereIsNoContextMenuForEntityType {
            get {
                return ResourceManager.GetString("ThereIsNoContextMenuForEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Action.
        /// </summary>
        public static string ToolbarButtonParentActionId {
            get {
                return ResourceManager.GetString("ToolbarButtonParentActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Action.
        /// </summary>
        public static string ToolbarButtonParentActionNotSelected {
            get {
                return ResourceManager.GetString("ToolbarButtonParentActionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format.
        /// </summary>
        public static string UrlInvalidFormat {
            get {
                return ResourceManager.GetString("UrlInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of URL should not exceed {5} characters!.
        /// </summary>
        public static string UrlMaxLengthExceeded {
            get {
                return ResourceManager.GetString("UrlMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter URL.
        /// </summary>
        public static string UrlNotEntered {
            get {
                return ResourceManager.GetString("UrlNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Height.
        /// </summary>
        public static string WindowHeight {
            get {
                return ResourceManager.GetString("WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Window Height.
        /// </summary>
        public static string WindowHeightIsNotEntered {
            get {
                return ResourceManager.GetString("WindowHeightIsNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of Window Height is not in acceptable range: from {0} to {1}.
        /// </summary>
        public static string WindowHeightIsNotInRange {
            get {
                return ResourceManager.GetString("WindowHeightIsNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Width.
        /// </summary>
        public static string WindowWidth {
            get {
                return ResourceManager.GetString("WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Window Width.
        /// </summary>
        public static string WindowWidthIsNotEntered {
            get {
                return ResourceManager.GetString("WindowWidthIsNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of Window Width is not in acceptable range: from {0} to {1}.
        /// </summary>
        public static string WindowWidthIsNotInRange {
            get {
                return ResourceManager.GetString("WindowWidthIsNotInRange", resourceCulture);
            }
        }
    }
}
