//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantumart.QP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DBStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quantumart.QP8.Resources.DBStrings", typeof(DBStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add application setting.
        /// </summary>
        public static string AddAppSetting {
            get {
                return ResourceManager.GetString("AddAppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load home page after logon.
        /// </summary>
        public static string AutoLoadHome {
            get {
                return ResourceManager.GetString("AutoLoadHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download records.
        /// </summary>
        public static string DownloadRecords {
            get {
                return ResourceManager.GetString("DownloadRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key #{0} length should not exceed 255 characters.
        /// </summary>
        public static string KeyMaxLengthExceeded {
            get {
                return ResourceManager.GetString("KeyMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key #{0} should be unique!.
        /// </summary>
        public static string KeyNotUnique {
            get {
                return ResourceManager.GetString("KeyNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Key #{0}!.
        /// </summary>
        public static string KeyRequired {
            get {
                return ResourceManager.GetString("KeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file if exists.
        /// </summary>
        public static string OverrideRecordsFile {
            get {
                return ResourceManager.GetString("OverrideRecordsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture single editor mode.
        /// </summary>
        public static string OverrideRecordsUser {
            get {
                return ResourceManager.GetString("OverrideRecordsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record actions into file.
        /// </summary>
        public static string RecordActions {
            get {
                return ResourceManager.GetString("RecordActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay records.
        /// </summary>
        public static string ReplayRecords {
            get {
                return ResourceManager.GetString("ReplayRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проигрывание записанных действий.
        /// </summary>
        public static string ReplayRecordsLabel {
            get {
                return ResourceManager.GetString("ReplayRecordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not allowed because of single editor mode.
        /// </summary>
        public static string SingeUserModeMessage {
            get {
                return ResourceManager.GetString("SingeUserModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on users synchronization with Active Directory.
        /// </summary>
        public static string UseAdSyncService {
            get {
                return ResourceManager.GetString("UseAdSyncService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CDC for system notifications.
        /// </summary>
        public static string UseCDC {
            get {
                return ResourceManager.GetString("UseCDC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use internal DPC.
        /// </summary>
        public static string UseDPC {
            get {
                return ResourceManager.GetString("UseDPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value #{0} length should not exceed 255 characters.
        /// </summary>
        public static string ValueMaxLengthExceeded {
            get {
                return ResourceManager.GetString("ValueMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Value #{0}!.
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
    }
}
