//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantumart.QP8.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quantumart.QP8.Resources.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected server error.
        /// </summary>
        public static string _500Error {
            get {
                return ResourceManager.GetString("500Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have no enough permissions to execute action &apos;{0}&apos;.
        /// </summary>
        public static string ActionIsNotAccessible {
            get {
                return ResourceManager.GetString("ActionIsNotAccessible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel selection.
        /// </summary>
        public static string CancelSelection {
            get {
                return ResourceManager.GetString("CancelSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decrease Value.
        /// </summary>
        public static string DecreaseValue {
            get {
                return ResourceManager.GetString("DecreaseValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have no enough permissions to execute action (type: &apos;{0}&apos;, entity type: &apos;{1}&apos;, ID: {2})..
        /// </summary>
        public static string EntityIsNotAccessible {
            get {
                return ResourceManager.GetString("EntityIsNotAccessible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When filling out the form appeared the following errors:.
        /// </summary>
        public static string ErrorSummary_FormErrors {
            get {
                return ResourceManager.GetString("ErrorSummary_FormErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide Visual Editor.
        /// </summary>
        public static string HideVisualEditor {
            get {
                return ResourceManager.GetString("HideVisualEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Increase Value.
        /// </summary>
        public static string IncreaseValue {
            get {
                return ResourceManager.GetString("IncreaseValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locked by.
        /// </summary>
        public static string LockedByUser {
            get {
                return ResourceManager.GetString("LockedByUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locking.
        /// </summary>
        public static string LockingGroup {
            get {
                return ResourceManager.GetString("LockingGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to -Value is not selected-.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make lock permanent.
        /// </summary>
        public static string PermanentLock {
            get {
                return ResourceManager.GetString("PermanentLock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permanent Lock.
        /// </summary>
        public static string PermanentLockSet {
            get {
                return ResourceManager.GetString("PermanentLockSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Visual Editor.
        /// </summary>
        public static string ShowVisualEditor {
            get {
                return ResourceManager.GetString("ShowVisualEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration variable SqlMetalPath cannot be empty..
        /// </summary>
        public static string SqlMetalPathEmpty {
            get {
                return ResourceManager.GetString("SqlMetalPathEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To Text Editor.
        /// </summary>
        public static string ToTextEditor {
            get {
                return ResourceManager.GetString("ToTextEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To Visual Editor.
        /// </summary>
        public static string ToVisualEditor {
            get {
                return ResourceManager.GetString("ToVisualEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string UserInfo_Label_LoggedInAs {
            get {
                return ResourceManager.GetString("UserInfo_Label_LoggedInAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string UserInfo_Link_Exit {
            get {
                return ResourceManager.GetString("UserInfo_Link_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ViewDownload {
            get {
                return ResourceManager.GetString("ViewDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are not authenticated.
        /// </summary>
        public static string YouAreNotAuthenticated {
            get {
                return ResourceManager.GetString("YouAreNotAuthenticated", resourceCulture);
            }
        }
    }
}
