//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantumart.QP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quantumart.QP8.Resources.NotificationStrings", typeof(NotificationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Notification.
        /// </summary>
        public static string AddNewNotification {
            get {
                return ResourceManager.GetString("AddNewNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Status.
        /// </summary>
        public static string AnyStatus {
            get {
                return ResourceManager.GetString("AnyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Parameters.
        /// </summary>
        public static string BasicParameters {
            get {
                return ResourceManager.GetString("BasicParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Field.
        /// </summary>
        public static string ChooseField {
            get {
                return ResourceManager.GetString("ChooseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Format.
        /// </summary>
        public static string ChooseFormat {
            get {
                return ResourceManager.GetString("ChooseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose template.
        /// </summary>
        public static string ChooseTemplate {
            get {
                return ResourceManager.GetString("ChooseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create notification because there are aggregated fields in the content.
        /// </summary>
        public static string ContentContainsAggregatedFields {
            get {
                return ResourceManager.GetString("ContentContainsAggregatedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Default Format.
        /// </summary>
        public static string CreateDefaultFormat {
            get {
                return ResourceManager.GetString("CreateDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sender  Name.
        /// </summary>
        public static string DefaultSenderName {
            get {
                return ResourceManager.GetString("DefaultSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one event.
        /// </summary>
        public static string EventNotSelected {
            get {
                return ResourceManager.GetString("EventNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External URL.
        /// </summary>
        public static string ExternalUrl {
            get {
                return ResourceManager.GetString("ExternalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter external URL!.
        /// </summary>
        public static string ExternalUrlNotEntered {
            get {
                return ResourceManager.GetString("ExternalUrlNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid external URL!.
        /// </summary>
        public static string ExternalUrlNotValid {
            get {
                return ResourceManager.GetString("ExternalUrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select field.
        /// </summary>
        public static string FieldNotSelected {
            get {
                return ResourceManager.GetString("FieldNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ForCreate {
            get {
                return ResourceManager.GetString("ForCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed Publication.
        /// </summary>
        public static string ForDelayedPublication {
            get {
                return ResourceManager.GetString("ForDelayedPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request On Demand.
        /// </summary>
        public static string ForFrontend {
            get {
                return ResourceManager.GetString("ForFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select format.
        /// </summary>
        public static string FormatIdNotEntered {
            get {
                return ResourceManager.GetString("FormatIdNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string ForModify {
            get {
                return ResourceManager.GetString("ForModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ForRemove {
            get {
                return ResourceManager.GetString("ForRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Changed.
        /// </summary>
        public static string ForStatusChanged {
            get {
                return ResourceManager.GetString("ForStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Partially Changed.
        /// </summary>
        public static string ForStatusPartiallyChanged {
            get {
                return ResourceManager.GetString("ForStatusPartiallyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide recipients from each other.
        /// </summary>
        public static string HideRecipients {
            get {
                return ResourceManager.GetString("HideRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Not Found (Id = {0}).
        /// </summary>
        public static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QP8 User.
        /// </summary>
        public static string QP8User {
            get {
                return ResourceManager.GetString("QP8User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone In History.
        /// </summary>
        public static string RadioEveryone {
            get {
                return ResourceManager.GetString("RadioEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail From Article Field.
        /// </summary>
        public static string RadioFromArticle {
            get {
                return ResourceManager.GetString("RadioFromArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RadioNone {
            get {
                return ResourceManager.GetString("RadioNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string RadioUser {
            get {
                return ResourceManager.GetString("RadioUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string RadioUserGroup {
            get {
                return ResourceManager.GetString("RadioUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Type.
        /// </summary>
        public static string ReceiverType {
            get {
                return ResourceManager.GetString("ReceiverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of E-mail should not exceed {0} characters!.
        /// </summary>
        public static string SenderEmailLengthExceeded {
            get {
                return ResourceManager.GetString("SenderEmailLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter sender e-mail!.
        /// </summary>
        public static string SenderEmailNotEntered {
            get {
                return ResourceManager.GetString("SenderEmailNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid sender e-mail!.
        /// </summary>
        public static string SenderEmailNotValid {
            get {
                return ResourceManager.GetString("SenderEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of login should not exceed {0} characters!.
        /// </summary>
        public static string SenderNameMaxLengthExceeded {
            get {
                return ResourceManager.GetString("SenderNameMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter sender name!.
        /// </summary>
        public static string SenderNameNotEntered {
            get {
                return ResourceManager.GetString("SenderNameNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Files As Attachments.
        /// </summary>
        public static string SendFiles {
            get {
                return ResourceManager.GetString("SendFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select template.
        /// </summary>
        public static string TemplateIdNotEntered {
            get {
                return ResourceManager.GetString("TemplateIdNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbind.
        /// </summary>
        public static string Unbind {
            get {
                return ResourceManager.GetString("Unbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification was unbinded from workflow.
        /// </summary>
        public static string UnbindedMessage {
            get {
                return ResourceManager.GetString("UnbindedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Sender Name.
        /// </summary>
        public static string UseDefaultSenderName {
            get {
                return ResourceManager.GetString("UseDefaultSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use QA_Mail component in QP7 Backend.
        /// </summary>
        public static string UseQaMail {
            get {
                return ResourceManager.GetString("UseQaMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use QP8 User Email.
        /// </summary>
        public static string UseQP8UserEmail {
            get {
                return ResourceManager.GetString("UseQP8UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user group.
        /// </summary>
        public static string UserGroupNotSelected {
            get {
                return ResourceManager.GetString("UserGroupNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user.
        /// </summary>
        public static string UserNotSelected {
            get {
                return ResourceManager.GetString("UserNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use service for sending.
        /// </summary>
        public static string UseService {
            get {
                return ResourceManager.GetString("UseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This notification is default and bound to workflow ({0})..
        /// </summary>
        public static string WarningString {
            get {
                return ResourceManager.GetString("WarningString", resourceCulture);
            }
        }
    }
}
