//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantumart.QP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisualEditorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisualEditorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quantumart.QP8.Resources.VisualEditorStrings", typeof(VisualEditorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New CSS Style.
        /// </summary>
        public static string AddNewCssStyle {
            get {
                return ResourceManager.GetString("AddNewCssStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New External CSS.
        /// </summary>
        public static string AddNewExternalCss {
            get {
                return ResourceManager.GetString("AddNewExternalCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New HTML Attribute.
        /// </summary>
        public static string AddNewHtmlAttribute {
            get {
                return ResourceManager.GetString("AddNewHtmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Visual Editor Plugin Command.
        /// </summary>
        public static string AddNewVisualEditorCommand {
            get {
                return ResourceManager.GetString("AddNewVisualEditorCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Visual Editor Plugin.
        /// </summary>
        public static string AddNewVisualEditorPlugin {
            get {
                return ResourceManager.GetString("AddNewVisualEditorPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Visual Editor Style.
        /// </summary>
        public static string AddNewVisualEditorStyle {
            get {
                return ResourceManager.GetString("AddNewVisualEditorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Attributes.
        /// </summary>
        public static string AttributesMessage {
            get {
                return ResourceManager.GetString("AttributesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one HTML-attribute is required!.
        /// </summary>
        public static string AttributesRequired {
            get {
                return ResourceManager.GetString("AttributesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command`s #{0} alias should be unique within its VE Plugin`s сommands.
        /// </summary>
        public static string CommandAliasDuplicate {
            get {
                return ResourceManager.GetString("CommandAliasDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of command`s #{0} Alias should not exceed 255 characters!.
        /// </summary>
        public static string CommandAliasMaxLengthExceeded {
            get {
                return ResourceManager.GetString("CommandAliasMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command`s #{0} Alias should be unique within all VE сommands!.
        /// </summary>
        public static string CommandAliasNonUnique {
            get {
                return ResourceManager.GetString("CommandAliasNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter alias for command #{0}!.
        /// </summary>
        public static string CommandAliasRequired {
            get {
                return ResourceManager.GetString("CommandAliasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command`s #{0} name should be unique within its VE Plugin`s сommands!.
        /// </summary>
        public static string CommandNameDuplicate {
            get {
                return ResourceManager.GetString("CommandNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command #{0} has invalid name format!.
        /// </summary>
        public static string CommandNameInvalidFormat {
            get {
                return ResourceManager.GetString("CommandNameInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Length of command`s #{0} name should not exceed 255 сharacters!.
        /// </summary>
        public static string CommandNameMaxLengthExceeded {
            get {
                return ResourceManager.GetString("CommandNameMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command`s #{0} name should be unique within all VE сommands.
        /// </summary>
        public static string CommandNameNonUnique {
            get {
                return ResourceManager.GetString("CommandNameNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name for command #{0}!.
        /// </summary>
        public static string CommandNameRequired {
            get {
                return ResourceManager.GetString("CommandNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some commands are not valid.
        /// </summary>
        public static string CommandNotValid {
            get {
                return ResourceManager.GetString("CommandNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one visual editor command is required!.
        /// </summary>
        public static string CommandsRequired {
            get {
                return ResourceManager.GetString("CommandsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External CSS.
        /// </summary>
        public static string ExternalCss {
            get {
                return ResourceManager.GetString("ExternalCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External CSS`s #{0} URL is duplicate.
        /// </summary>
        public static string ExternalCssUrlDuplicate {
            get {
                return ResourceManager.GetString("ExternalCssUrlDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External CSS`s #{0} URL should not exceed 255 characters!.
        /// </summary>
        public static string ExternalCssUrlMaxLengthExceeded {
            get {
                return ResourceManager.GetString("ExternalCssUrlMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External CSS`s #{0} URL is not valid.
        /// </summary>
        public static string ExternalCssUrlNotValid {
            get {
                return ResourceManager.GetString("ExternalCssUrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter URL for External CSS #{0}!.
        /// </summary>
        public static string ExternalCssUrlRequired {
            get {
                return ResourceManager.GetString("ExternalCssUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        public static string Formats {
            get {
                return ResourceManager.GetString("Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string HeaderAlias {
            get {
                return ResourceManager.GetString("HeaderAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string HeaderValue {
            get {
                return ResourceManager.GetString("HeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string IsFormat {
            get {
                return ResourceManager.GetString("IsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string IsSystem {
            get {
                return ResourceManager.GetString("IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides Tag.
        /// </summary>
        public static string OverridesTag {
            get {
                return ResourceManager.GetString("OverridesTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Tag has invalid format.
        /// </summary>
        public static string OverrideTagInvalidFormat {
            get {
                return ResourceManager.GetString("OverrideTagInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Override Tag should not exceed 20 characters.
        /// </summary>
        public static string OverrideTagMaxLengthExceeded {
            get {
                return ResourceManager.GetString("OverrideTagMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Element Class.
        /// </summary>
        public static string RootElementClass {
            get {
                return ResourceManager.GetString("RootElementClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Settings.
        /// </summary>
        public static string StyleSettings {
            get {
                return ResourceManager.GetString("StyleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string StylesMessage {
            get {
                return ResourceManager.GetString("StylesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Style is required!.
        /// </summary>
        public static string StylesRequired {
            get {
                return ResourceManager.GetString("StylesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual editor style (Id = {0}) can`t be removed because it is a system VE style.
        /// </summary>
        public static string SystemWarning {
            get {
                return ResourceManager.GetString("SystemWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag has invalid format.
        /// </summary>
        public static string TagInvalidFormat {
            get {
                return ResourceManager.GetString("TagInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Tag should not exceed 20 characters.
        /// </summary>
        public static string TagMaxLengthExceeded {
            get {
                return ResourceManager.GetString("TagMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Tag!.
        /// </summary>
        public static string TagNotEntered {
            get {
                return ResourceManager.GetString("TagNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format.
        /// </summary>
        public static string UrlPrefixInvalidFormat {
            get {
                return ResourceManager.GetString("UrlPrefixInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of URL should not exceed {5} characters.
        /// </summary>
        public static string UrlPrefixMaxLengthExceeded {
            get {
                return ResourceManager.GetString("UrlPrefixMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}`s #{1} Name should be unique within its VE Style`s {2}.
        /// </summary>
        public static string VeStyleAggrListItemNameDuplicate {
            get {
                return ResourceManager.GetString("VeStyleAggrListItemNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}`s #{1} Name has invalid format.
        /// </summary>
        public static string VeStyleAggrListItemNameInvalidFormat {
            get {
                return ResourceManager.GetString("VeStyleAggrListItemNameInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {0}`s #{1} Name length should not exceed 255 characters.
        /// </summary>
        public static string VeStyleAggrListItemNameMaxLengthExceeded {
            get {
                return ResourceManager.GetString("VeStyleAggrListItemNameMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0}`s #{1} Name!.
        /// </summary>
        public static string VeStyleAggrListItemNameRequired {
            get {
                return ResourceManager.GetString("VeStyleAggrListItemNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {0}`s #{1} Value length should not exceed 255 characters.
        /// </summary>
        public static string VeStyleAggrListItemValueMaxLengthExceeded {
            get {
                return ResourceManager.GetString("VeStyleAggrListItemValueMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0}`s #{1} Value!.
        /// </summary>
        public static string VeStyleAggrListItemValueRequired {
            get {
                return ResourceManager.GetString("VeStyleAggrListItemValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Editor Plugin is not found (Id = {0}).
        /// </summary>
        public static string VisualEditorPluginNotFound {
            get {
                return ResourceManager.GetString("VisualEditorPluginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Editor Style is not found (Id = {0}).
        /// </summary>
        public static string VisualEditorStyleNotFound {
            get {
                return ResourceManager.GetString("VisualEditorStyleNotFound", resourceCulture);
            }
        }
    }
}
