if not exists(select * from sys.tables where name = 'PLUGIN_VERSION')
BEGIN
	CREATE TABLE dbo.PLUGIN_VERSION(
		ID numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
		PLUGIN_ID numeric(18,0) NOT NULL
		    CONSTRAINT FK_PLUGIN_VERSION_PLUGIN_ID FOREIGN KEY REFERENCES dbo.PLUGIN (ID) ON DELETE CASCADE,
        CONTRACT nvarchar(max) NOT NULL,
	    CREATED datetime NOT NULL,
	    MODIFIED datetime NOT NULL,
	    LAST_MODIFIED_BY numeric(18, 0) NOT NULL
	        CONSTRAINT FK_PLUGIN_VERSION_LAST_MODIFIED_BY FOREIGN KEY REFERENCES dbo.USERS (USER_ID)
	) ON [PRIMARY]

END
GO
--drop table plugin_version