if not exists(select * from sys.tables where name = 'PLUGIN_FIELD_VALUE')
BEGIN
	CREATE TABLE dbo.PLUGIN_FIELD_VALUE(
		ID numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
		PLUGIN_FIELD_ID numeric(18,0) NOT NULL
		    CONSTRAINT FK_PLUGIN_FIELD_VALUE_PLUGIN_FIELD_ID FOREIGN KEY REFERENCES dbo.PLUGIN_FIELD (ID) ON DELETE CASCADE,
		CONTENT_ID numeric(18,0) NULL
		    CONSTRAINT FK_PLUGIN_FIELD_VALUE_CONTENT_ID FOREIGN KEY REFERENCES dbo.CONTENT (CONTENT_ID),
		SITE_ID numeric(18,0) NULL
		    CONSTRAINT FK_PLUGIN_FIELD_VALUE_SITE_ID FOREIGN KEY REFERENCES dbo.SITE (SITE_ID),
		CONTENT_ATTRIBUTE_ID numeric(18,0) NULL
		    CONSTRAINT FK_PLUGIN_FIELD_VALUE_CONTENT_ATTRIBUTE_ID FOREIGN KEY REFERENCES dbo.CONTENT_ATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
        VALUE nvarchar(max) NULL
	) ON [PRIMARY]

END
--drop table plugin_field_value