if not exists(select * from sys.tables where name = 'ACCESS_TOKEN')
BEGIN
	CREATE TABLE [dbo].[ACCESS_TOKEN](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[UserId] [int] NOT NULL,
		[Token] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
		[ExpirationDate] [datetime] NULL,
		[Application] [nvarchar](200) NOT NULL,
		[SessionId] [int] NOT NULL,
	CONSTRAINT [PK_ACCESS_TOKEN] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]	
END


if not exists (select * from sys.indexes where name = 'IX_ACCESS_TOKEN_Session')
BEGIN
	CREATE UNIQUE NONCLUSTERED INDEX [IX_ACCESS_TOKEN_Session] ON [dbo].[ACCESS_TOKEN]
	(
		[UserId] ASC,
		[Application] ASC,
		[SessionId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END

if not exists (select * from sys.indexes where name = 'IX_ACCESS_TOKEN_Token')
BEGIN
	CREATE UNIQUE NONCLUSTERED INDEX [IX_ACCESS_TOKEN_Token] ON [dbo].[ACCESS_TOKEN]
	(
		[Token] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	ALTER TABLE [dbo].[ACCESS_TOKEN] ADD  CONSTRAINT [DF_ACCESS_TOKEN_Token]  DEFAULT (newid()) FOR [Token]
END