IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONTENT_ITEM_VERSION' AND COLUMN_NAME = 'STATUS_TYPE_ID')
BEGIN
    ALTER TABLE CONTENT_ITEM_VERSION ADD STATUS_TYPE_ID NUMERIC(18,0) NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONTENT_ITEM_VERSION' AND COLUMN_NAME = 'ARCHIVE')
BEGIN
    ALTER TABLE CONTENT_ITEM_VERSION ADD ARCHIVE BIT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONTENT_ITEM_VERSION' AND COLUMN_NAME = 'VISIBLE')
BEGIN
    ALTER TABLE CONTENT_ITEM_VERSION ADD VISIBLE BIT NULL
END
GO

