IF NOT EXISTS(select * from sys.tables where name = 'EXTERNAL_WORKFLOW')
BEGIN
    CREATE TABLE dbo.EXTERNAL_WORKFLOW(
        ID numeric(18, 0) IDENTITY(1,1),
        CREATED datetime2 NOT NULL,
        CREATED_BY varchar(100) NOT NULL,
        PROCESS_ID nvarchar(36) NOT NULL,
        ARTICLE_NAME nvarchar(255) NOT NULL,
        WORKFLOW_NAME nvarchar(255) NOT NULL,
        ARTICLE_ID numeric(18, 0) NOT NULL,
        WORKFLOW_ID numeric(18, 0) NOT NULL,
        CONSTRAINT PK_EXTERNAL_WORKFLOW PRIMARY KEY(ID),
        CONSTRAINT UQ_EXTERNAL_WORKFLOW_PROCESS_ID UNIQUE(PROCESS_ID)
    ) ON [PRIMARY]
END
GO

IF NOT EXISTS(select * from sys.tables where name = 'EXTERNAL_WORKFLOW_STATUS')
BEGIN
    CREATE TABLE dbo.EXTERNAL_WORKFLOW_STATUS(
        ID numeric(18, 0) IDENTITY(1,1),
        EXTERNAL_WORKFLOW_ID numeric(18, 0),
        STATUS varchar(255) NOT NULL,
        CREATED datetime2 NOT NULL,
        CREATED_BY varchar(100) NOT NULL,
        CONSTRAINT PK_EXTERNAL_WORKFLOW_STATUS PRIMARY KEY(ID),
        CONSTRAINT FK_EXTERNAL_WORKFLOW_STATUS_EXTERNAL_WORKFLOW_ID FOREIGN KEY (EXTERNAL_WORKFLOW_ID) REFERENCES dbo.EXTERNAL_WORKFLOW(ID)
    ) ON [PRIMARY]
END
GO

IF NOT EXISTS(select * from sys.tables where name = 'EXTERNAL_WORKFLOW_IN_PROGRESS')
BEGIN
    CREATE TABLE dbo.EXTERNAL_WORKFLOW_IN_PROGRESS(
        ID numeric(18, 0) IDENTITY(1,1),
        EXTERNAL_WORKFLOW_ID numeric(18, 0) NOT NULL,
        CURRENT_STATUS numeric(18, 0) NOT NULL,
        CONSTRAINT PK_EXTERNAL_WORKFLOW_IN_PROGRESS PRIMARY KEY(ID),
        CONSTRAINT UQ_EXTERNAL_WORKFLOW_IN_PROGRESS_EXTERNAL_WORKFLOW_ID UNIQUE(EXTERNAL_WORKFLOW_ID),
        CONSTRAINT FK_EXTERNAL_WORKFLOW_IN_PROGRESS_EXTERNAL_WORKFLOW_ID FOREIGN KEY (EXTERNAL_WORKFLOW_ID) REFERENCES dbo.EXTERNAL_WORKFLOW(ID),
        CONSTRAINT FK_EXTERNAL_WORKFLOW_IN_PROGRESS_CURRENT_STATUS FOREIGN KEY (CURRENT_STATUS) REFERENCES dbo.EXTERNAL_WORKFLOW_STATUS(ID),
    ) ON [PRIMARY]
END
GO
