if not exists(select * from INFORMATION_SCHEMA.COLUMNS where COLUMN_NAME = 'TEMPLATE_ID' and TABLE_NAME = 'NOTIFICATIONS')
    alter table [NOTIFICATIONS]
    add [TEMPLATE_ID] numeric(18,0) NULL

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where COLUMN_NAME = 'HIDE_RECIPIENTS' and TABLE_NAME = 'NOTIFICATIONS')
    alter table [NOTIFICATIONS] add [HIDE_RECIPIENTS] BIT NOT NULL DEFAULT 0
