if not exists(select * from INFORMATION_SCHEMA.COLUMNS where COLUMN_NAME = 'CAN_MANAGE_SCHEDULED_TASKS' and TABLE_NAME = 'USER_GROUP')
    alter table [USER_GROUP]
    add [CAN_MANAGE_SCHEDULED_TASKS] bit NOT NULL CONSTRAINT [DF_USER_GROUP_CAN_MANAGE_SCHEDULED_TASKS] DEFAULT ((0))
GO
