IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[WORKFLOW]') AND name = 'IS_DEFAULT')
  ALTER TABLE [dbo].[WORKFLOW] ADD [IS_DEFAULT] [bit] NOT NULL CONSTRAINT DF_WORKFLOW_IS_DEFAULT DEFAULT 0
