//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Quantumart.QP8.DAL.Entities
{

    // ReSharper disable CollectionNeverUpdated.Global
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    // ReSharper disable UnusedAutoPropertyAccessor.Global
    public partial class AppSettingsDAL
    {

        public string Key { get; set; }
        public string Value { get; set; }
    }
        public class AppSettingsDALConfiguration : IEntityTypeConfiguration<AppSettingsDAL>
        {
            public void Configure(EntityTypeBuilder<AppSettingsDAL> builder)
            {
                builder.ToTable("APP_SETTINGS");

                builder.Property(x => x.Value).HasColumnName("VALUE");
				builder.Property(x => x.Key).HasColumnName("KEY");


                builder.HasKey(x => x.Key);


            }
        }
}
