//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Quantumart.QP8.DAL.Entities
{

    // ReSharper disable CollectionNeverUpdated.Global
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    // ReSharper disable UnusedAutoPropertyAccessor.Global
    public partial class DangerousActionsDAL
    {

        public string ActionName { get; set; }
        public string EntityName { get; set; }
        public decimal Id { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime Performed { get; set; }
        public string Description { get; set; }
    }
        public class DangerousActionsDALConfiguration : IEntityTypeConfiguration<DangerousActionsDAL>
        {
            public void Configure(EntityTypeBuilder<DangerousActionsDAL> builder)
            {
                builder.ToTable("DANGEROUS_ACTIONS");

                builder.Property(x => x.ActionName).HasColumnName("ACTION_NAME");
				builder.Property(x => x.EntityName).HasColumnName("ENTITY_NAME");
				builder.Property(x => x.Id).HasColumnName("ID");
				builder.Property(x => x.UserId).HasColumnName("USER_ID");
				builder.Property(x => x.Performed).HasColumnName("PERFORMED");
				builder.Property(x => x.Description).HasColumnName("DESCRIPTION");


                builder.HasKey(x => x.Performed);


            }
        }
}
