//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Quantumart.QP8.DAL.Entities
{

    // ReSharper disable CollectionNeverUpdated.Global
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    // ReSharper disable UnusedAutoPropertyAccessor.Global
    public partial class ItemToItemVersionDAL
    {

        public decimal ArticleVersionId { get; set; }
        public decimal FieldId { get; set; }
        public decimal LinkedItemId { get; set; }

        public FieldDAL Field { get; set; }
        public ArticleDAL Article { get; set; }
        public ArticleVersionDAL ArticleVersion { get; set; }
    }
        public class ItemToItemVersionDALConfiguration : IEntityTypeConfiguration<ItemToItemVersionDAL>
        {
            public void Configure(EntityTypeBuilder<ItemToItemVersionDAL> builder)
            {
                builder.ToTable("item_to_item_version");

                builder.Property(x => x.ArticleVersionId).HasColumnName("content_item_version_id");
				builder.Property(x => x.FieldId).HasColumnName("attribute_id");
				builder.Property(x => x.LinkedItemId).HasColumnName("linked_item_id");


                builder.HasKey(x => new { x.ArticleVersionId, x.FieldId, x.LinkedItemId });


                builder.HasOne(x => x.Field).WithMany(y => y.ItemToItemVersion).HasForeignKey(x => x.FieldId);
    			builder.HasOne(x => x.Article).WithMany(y => y.ItemToItemVersions).HasForeignKey(x => x.LinkedItemId);
    			builder.HasOne(x => x.ArticleVersion).WithMany(y => y.ItemToItemVersion).HasForeignKey(x => x.ArticleVersionId);

            }
        }
}
