//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Quantumart.QP8.DAL.Entities
{

    // ReSharper disable CollectionNeverUpdated.Global
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    // ReSharper disable UnusedAutoPropertyAccessor.Global
    public partial class SiteFolderPermissionDAL :  IQpEntityObject
    {

        public decimal FolderId { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<decimal> GroupId { get; set; }
        public decimal PermissionLevelId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public decimal LastModifiedBy { get; set; }
        public decimal Id { get; set; }

        public SiteFolderDAL Folder { get; set; }
        public UserGroupDAL Group { get; set; }
        public PermissionLevelDAL PermissionLevel { get; set; }
        public UserDAL User { get; set; }
        public UserDAL LastModifiedByUser { get; set; }
    }
        public class SiteFolderPermissionDALConfiguration : IEntityTypeConfiguration<SiteFolderPermissionDAL>
        {
            public void Configure(EntityTypeBuilder<SiteFolderPermissionDAL> builder)
            {
                builder.ToTable("FOLDER_ACCESS");

                builder.Property(x => x.FolderId).HasColumnName("FOLDER_ID");
				builder.Property(x => x.UserId).HasColumnName("USER_ID");
				builder.Property(x => x.GroupId).HasColumnName("GROUP_ID");
				builder.Property(x => x.PermissionLevelId).HasColumnName("PERMISSION_LEVEL_ID");
				builder.Property(x => x.Created).HasColumnName("CREATED");
				builder.Property(x => x.Modified).HasColumnName("MODIFIED");
				builder.Property(x => x.LastModifiedBy).HasColumnName("LAST_MODIFIED_BY");
				builder.Property(x => x.Id).HasColumnName("FOLDER_ACCESS_ID").ValueGeneratedOnAdd();


                builder.HasKey(x => x.Id);

                builder.HasOne(x => x.Folder).WithMany(y => y.FolderAccess).HasForeignKey(x => x.FolderId);
    			builder.HasOne(x => x.Group).WithMany(y => y.FolderAccess).HasForeignKey(x => x.GroupId);
    			builder.HasOne(x => x.PermissionLevel).WithMany(y => y.FolderAccess).HasForeignKey(x => x.PermissionLevelId);
    			builder.HasOne(x => x.User).WithMany(y => y.FolderAccess).HasForeignKey(x => x.UserId);
    			builder.HasOne(x => x.LastModifiedByUser).WithMany().HasForeignKey(x => x.LastModifiedBy);

            }
        }
}
