//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Quantumart.QP8.DAL.Entities
{

    // ReSharper disable CollectionNeverUpdated.Global
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    // ReSharper disable UnusedAutoPropertyAccessor.Global
    public partial class UnionAttrDAL
    {

        public decimal VirtualFieldId { get; set; }
        public decimal UnionFieldId { get; set; }
        public Nullable<bool> EF_FIX { get; set; }

        public FieldDAL UnionField { get; set; }
        public FieldDAL VirtualField { get; set; }
    }
        public class UnionAttrDALConfiguration : IEntityTypeConfiguration<UnionAttrDAL>
        {
            public void Configure(EntityTypeBuilder<UnionAttrDAL> builder)
            {
                builder.ToTable("union_attrs");

                builder.Property(x => x.EF_FIX).HasColumnName("EF_FIX");
				builder.Property(x => x.VirtualFieldId).HasColumnName("virtual_attr_id");
				builder.Property(x => x.UnionFieldId).HasColumnName("union_attr_id");


                builder.HasKey(x => new { x.VirtualFieldId, x.UnionFieldId });


                builder.HasOne(x => x.UnionField).WithMany().HasForeignKey(x => x.UnionFieldId);
    			builder.HasOne(x => x.VirtualField).WithMany().HasForeignKey(x => x.VirtualFieldId);

            }
        }
}
