// Code generated by a template
using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.SqlClient;

namespace Quantumart.QP8.EntityFramework6.Data
{
	public class EF6ModelConnectionScope
	{

	}
}
