ALTER TABLE content_item_version ADD COLUMN IF NOT EXISTS STATUS_TYPE_ID NUMERIC NULL;
ALTER TABLE content_item_version ADD COLUMN IF NOT EXISTS ARCHIVE BOOLEAN NULL;
ALTER TABLE content_item_version ADD COLUMN IF NOT EXISTS VISIBLE BOOLEAN NULL;

