trigger:
  - master

jobs:
  - job: BuildConsoleDbUpdateAndPublish
    displayName: "Build docker image"
    pool:
      name: "MSCBUILD03"
      demands:
        - agent.os -equals Linux
        - docker
    steps:
      - checkout: self
        clean: true
        
      - task: Shell++@0
        displayName: 'Set git variables'
        inputs:
          type: 'InlineScript'
          failOnStandardError: true
          script: |
            sha=$(git rev-parse --verify HEAD --short | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            echo '##vso[task.setvariable variable=GitVersion.Sha;]'$sha
                
            tag=$(git describe --abbrev=0 --tags | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            echo '##vso[task.setvariable variable=GitVersion.Tag;]'$tag

            cnt=$(git rev-list HEAD --count $tag..HEAD)
            echo '##vso[task.setvariable variable=GitVersion.CommitsSinceTag;]'$cnt

      - task: Shell++@0
        displayName: 'Create projectfiles.tar'
        inputs:
          type: "FilePath"
          scriptPath: "create_tar.sh"

      - task: Docker@0
        displayName: 'Build an image'
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryConnection: 'spbdocker03'
          action: 'Build an image'
          dockerFile: 'Dockerfile.ConsoleDbUpdate'
          buildArguments: |
            SERVICE_VERSION=$(GitVersion.Tag).$(GitVersion.CommitsSinceTag)-$(GitVersion.Sha)
          imageName: '$(service.imageName):$(GitVersion.Tag).$(GitVersion.CommitsSinceTag)'

      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryConnection: spbdocker03
          action: 'Push an image'
          imageName: '$(service.imageName):$(GitVersion.Tag).$(GitVersion.CommitsSinceTag)'