IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONTENT_ATTRIBUTE' AND COLUMN_NAME = 'TRACE_IMPORT')
BEGIN
    ALTER TABLE CONTENT_ATTRIBUTE ADD TRACE_IMPORT BIT NOT NULL CONSTRAINT DF_CONTENT_ATTRIBUITE_TRACE_IMPORT DEFAULT 0
END
GO