IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONTENT' AND COLUMN_NAME = 'TRACE_IMPORT_SCRIPT')
BEGIN
    ALTER TABLE CONTENT ADD TRACE_IMPORT_SCRIPT NVARCHAR(MAX) NULL
END
GO
