exec qp_drop_existing 'SYSTEM_NOTIFICATION_QUEUE', 'IsUserTable'
GO

CREATE TABLE [dbo].[CdcLastExecutedLsn] (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [ProviderUrl] [nvarchar](1024) NOT NULL,
  [TransactionLsn] [varchar](22) NULL,
  [TransactionDate] [datetime] NULL,
  [LastExecutedLsn] [varchar](22) NOT NULL,
  PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

ALTER TABLE [dbo].[SYSTEM_NOTIFICATION_QUEUE] ADD  CONSTRAINT [DF_SYSTEM_NOTIFICATION_QUEUE_CREATED]  DEFAULT (getdate()) FOR [CREATED]
GO

ALTER TABLE [dbo].[SYSTEM_NOTIFICATION_QUEUE] ADD  CONSTRAINT [DF_SYSTEM_NOTIFICATION_QUEUE_TRIES]  DEFAULT ((0)) FOR [TRIES]
GO

ALTER TABLE [dbo].[SYSTEM_NOTIFICATION_QUEUE] ADD  CONSTRAINT [DF_SYSTEM_NOTIFICATION_QUEUE_SENT]  DEFAULT ((0)) FOR [SENT]
GO

ALTER TABLE [dbo].[SYSTEM_NOTIFICATION_QUEUE] ADD  CONSTRAINT [DF_SYSTEM_NOTIFICATION_QUEUE_MODIFIED]  DEFAULT (getdate()) FOR [MODIFIED]
GO
